name: Release

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Where to deploy
        options: 
        - staging
        - production

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout
      id-token: write # This is required for requesting the JWT
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check licenses
        run: pnpm license-check

      - name: GraphQL Codegen
        run: pnpm graphql-codegen

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Compile project
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm build

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: commonassoconnectfrcglobalacr.azurecr.io
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Dockerize & Push to Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            commonassoconnectfrcglobalacr.azurecr.io/swan-partner-frontend:${{ github.event.inputs.target }}-latest
            commonassoconnectfrcglobalacr.azurecr.io/swan-partner-frontend:${{ github.event.inputs.target }}-${{ github.sha }}

      - name: Deploy to Azure Web App - Production
        if: ${{ github.event.inputs.target == 'production' }}
        id: deploy-to-webapp-production
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: web-assoconnect-frc-prod-swan
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PRODUCTION }}
          images: 'commonassoconnectfrcglobalacr.azurecr.io/swan-partner-frontend:${{ github.event.inputs.target }}-${{ github.sha }}'

      - name: Deploy to Azure Web App - Networks - Production
        if: ${{ github.event.inputs.target == 'production' }}
        id: deploy-to-webapp-production
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: web-assoconnect-frc-prod-swan-networks
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_NETWORKS_PRODUCTION }}
          images: 'commonassoconnectfrcglobalacr.azurecr.io/swan-partner-frontend:${{ github.event.inputs.target }}-${{ github.sha }}'

      - name: Deploy to Azure Web App - Staging
        if: ${{ github.event.inputs.target == 'staging' }}
        id: deploy-to-webapp-staging
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: web-assoconnect-frc-prod-swan
          slot-name: staging
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          images: 'commonassoconnectfrcglobalacr.azurecr.io/swan-partner-frontend:${{ github.event.inputs.target }}-${{ github.sha }}'

      - name: Deploy to Azure Web App - Networks - Staging
        if: ${{ github.event.inputs.target == 'staging' }}
        id: deploy-to-webapp-staging
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: web-assoconnect-frc-prod-swan-networks
          slot-name: staging
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_NETWORKS_STAGING }}
          images: 'commonassoconnectfrcglobalacr.azurecr.io/swan-partner-frontend:${{ github.event.inputs.target }}-${{ github.sha }}'

          
